### PR TITLE
feat: publish the node.js client library from the new package structure

### PR DESCRIPTION
**Pull request by cprice404**
This commit updates the publish scripts to publish the node.js
SDK package in addition to the core package.  We add a script
to wait for the core package to be available on node.js, then
update the dependency in the nodejs SDK package to use the newly
released version of core, then publish the nodejs package.

### CODE REVIEW

**Review by bruuuuuuuce — APPROVED** [review]
:shipit:

**Comment by cprice404** [comment]
had to rebase

**Comment by bruuuuuuuce** [comment]
@cprice404 looks like tests are failing

**Comment by cprice404** [comment]
> @cprice404 looks like tests are failing

there is some weird intermittent test failure happening where the web sdk List collection methods show up as "undefined".  then if you re-run the tests they pass.  We need to get to the bottom of it; my best guess for now is that there is some github npm cache that is occasionally linking us against older commits of the core lib or something.

We need to figure it out if it keeps happening but for now I think I want to just get the release process working again first.

**Review by bruuuuuuuce — APPROVED** [review]
:shipit:

**Review by pgautier404 — APPROVED** [review]

**Pull request merged**
